language: php

php:
    - 5.5
    - 5.6

before_script:
    - sudo echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    #app composer required
    -  composer self-update
    -  composer install --dev --no-interaction --prefer-dist
 
script: 
    - phpunit --configuration phpunit.xml.dist --coverage-text

matrix:
  allow_failures:
    - php: 5.6

  fast_finish: true
