language: php

php:
    - 5.5
    - 5.6

before_script:
    - sudo apt-get install apache2
    - sudo echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sudo a2enmod actions
    - sudo a2enmod rewrite
    - sudo cp -f travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
    - sudo php -q
                    <?php
                            $file = @file_get_contents("/etc/apache2/sites-available/default", "r");
                            echo $file;
                    ?>
    - sudo service apache2 restart
    #app composer required
    - composer install --dev --no-interaction --prefer-dist
 
script: 
    - phpunit --configuration phpunit.xml.dist --coverage-text

matrix:
  allow_failures:
    - php: 5.6

  fast_finish: true
