language: php

php:
    - 5.5

before_script:
                - composer install --dev --no-interaction
                - export PATH=$PATH:/home/travis/build/Ferreiramg/Repo-teste/vendor/bin/
                - propel model:build --input-dir="opt" --output-dir="ServiceLayer/table-gateway"
                - composer dump-autoload
 
script: 
        - phpunit --configuration phpunit.xml.dist --coverage-text
