language: php

php:
    - 5.5

before_script:
                - sudo apt-get install apache2
                - sudo a2enmod actions
                - sudo a2enmod rewrite
                - sudo cp -f travis-ci-apache /etc/apache2/sites-available/default
                - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
                - sudo service apache2 restart
                #app composer required
                - composer install --dev --no-interaction
                - export PATH=$PATH:/home/travis/build/Ferreiramg/Repo-teste/vendor/bin/
                - propel model:build --input-dir="opt" --output-dir="ServiceLayer/table-gateway"
                - composer dump-autoload
 
script: 
        - phpunit --configuration phpunit.xml.dist --coverage-text
